Support generating bootstrapping keys at the server side.
awslabs/aws-cppwrapper-lattigo pull request #21
Opened 2024-03-18 16:25 UTC by Guy-Moshkowich

*Issue #, if available:* N/A

*Description of changes:*
This PR enable generating bootstrapping keys at the server side. Current API, requires providing the secret key which is not available in the server side. The new implementation require the generation of bootstrapping switching key pair and their marshaling.

1) Add support for un/marshal SwitchingKey 
2) Generate bootstrapping keys without secret key based on Lattigo v4.1.0 implementation https://github.com/tuneinsight/lattigo/blob/adf762375670e412bab261cd7ffff9ca03777ad5/ckks/bootstrapping/bootstrapper.go#L78
3) Enable generating conjugate rotation. Lattigo original API already supports this feature but the C++ wrapper used to call it with fixed "false" value. This is useful for generating bootstrapping keys manually.
4) Deprecated a function that accept unused parameters and fix bootstrapping example to use the fixed function

All the C++ wrapper examples are running successfully with this PR changes.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-03-28 22:23 UTC, crockeea requested changes
Thank you so much for this contribution!

2024-03-28 22:23 UTC, crockeea commented on src/gowrapper/ckks/keygen.go
> +func lattigo_genBootstrappingKey(keygenHandle Handle5, paramHandle Handle5, btpParamsHandle Handle5, skHandle Handle5) Handle5 {
Nice catch.

2024-03-28 22:23 UTC, crockeea commented on src/latticpp/ckks/keygen.cpp
> +    }
I'm not terribly concerned with backwards compatibility; I suggest we just kill this function.
```suggestion
```

2024-03-28 22:23 UTC, crockeea commented on src/latticpp/ckks/keygen.h
> +    RotationKeys genRotationKeysForRotations(const KeyGenerator &keygen, const SecretKey &sk, std::vector<int> shifts, int includeConjugate);
Nit: We could just keep this API and set the default argument for `includeConjugate` to `false`.

2024-03-28 22:23 UTC, crockeea commented on src/latticpp/ckks/keygen.h
> +    // DEPRACATED: use genBootstrappingKey with the same list of parameters excluding RelinearizationKey, RotationKeys
```suggestion
```

2024-03-29 07:54 UTC, Guy-Moshkowich commented
Thank you for taking the time to review and for the good comments. I've fixed all of them.

2024-03-29 18:40 UTC, crockeea approved these changes

2024-03-29 18:41 UTC, merged